version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: kannankani/reverseproxy 
  backend_user:
    build:
      context: ../../04-restapi-user
    image: kannankani/udacity-restapi-user
  backend_feed:
    build:
      context: ../../03-restapi-feed  
    image: kannankani/udacity-restapi-feed
  frontend:
    build:
      context: ../../02-frontend  
    image: kannankani/udacity-frontend
